# Generated by Django 3.2.4 on 2021-06-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_branch_brimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='BRtitle',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='BRImg',
            field=models.ImageField(upload_to='img/branchs'),
        ),
    ]
