# Generated by Django 3.2.4 on 2021-06-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_alter_branch_brimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(default='', upload_to='static/pdf/Books'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='Bdescrip',
            field=models.TextField(max_length=200, verbose_name='Desciption'),
        ),
    ]
