# Generated by Django 3.2.4 on 2021-06-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_auto_20210628_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Bclass',
            field=models.CharField(choices=[('اﻷول', 'اﻷول'), ('الثاني ', 'الثاني '), ('الثالث', 'الثالث'), ('الرابع', 'الرابع'), ('الخامس', 'الخامس'), ('السادس', 'السادس'), ('السابع', 'السابع'), ('الثامن', 'الثامن'), ('التاسع', 'التاسع'), ('العاشر', 'العاشر')], max_length=20, verbose_name='Semester'),
        ),
    ]
