# Generated by Django 3.2.4 on 2021-06-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_alter_book_bclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(null=True, upload_to='static/pdf/Books'),
        ),
    ]
