# Generated by Django 3.2.4 on 2021-07-01 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_alter_book_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Bclass',
            field=models.CharField(choices=[('اﻷول', 'اﻷول'), ('الثاني ', 'الثاني '), ('الثالث', 'الثالث'), ('الرابع', 'الرابع'), ('الخامس', 'الخامس'), ('السادس', 'السادس'), ('السابع', 'السابع'), ('الثامن', 'الثامن'), ('التاسع', 'التاسع'), ('العاشر', 'العاشر')], max_length=20, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Bcollge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college', verbose_name='الكلية'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Bdepart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.department', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Btitle',
            field=models.CharField(max_length=200, verbose_name='عنوان الكتاب'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='BRImg',
            field=models.ImageField(upload_to='static/img/branchs', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='BRdescrip',
            field=models.TextField(max_length=1000, verbose_name='وصف الفرع'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='BRtitle',
            field=models.CharField(max_length=200, verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='college',
            name='CLdepart',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=200, verbose_name='عدد الأقسام'),
        ),
        migrations.AlterField(
            model_name='college',
            name='CLdescrip',
            field=models.TextField(max_length=1000, verbose_name='وصف الكلية'),
        ),
        migrations.AlterField(
            model_name='college',
            name='CLtitle',
            field=models.CharField(max_length=200, verbose_name='اسم الكلية'),
        ),
        migrations.AlterField(
            model_name='department',
            name='Dcollege',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.college', verbose_name='الكلية'),
        ),
        migrations.AlterField(
            model_name='department',
            name='Dsystem',
            field=models.CharField(choices=[('نظام سنوي', ' نظام سنوي'), ('نظام الفصول', 'نظام الفصول')], max_length=200, verbose_name='نظام الدراسة'),
        ),
        migrations.AlterField(
            model_name='department',
            name='Dtitle',
            field=models.CharField(max_length=200, verbose_name='القسم'),
        ),
    ]
