# Generated by Django 3.2.4 on 2021-06-30 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_alter_book_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Bclass',
            field=models.CharField(choices=[('اﻷول', 'اﻷول'), ('الثاني ', 'الثاني '), ('الثالث', 'الثالث'), ('الرابع', 'الرابع'), ('الخامس', 'الخامس'), ('السادس', 'السادس'), ('السابع', 'السابع'), ('الثامن', 'الثامن'), ('التاسع', 'التاسع'), ('العاشر', 'العاشر')], max_length=20, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Bcollge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college', verbose_name='الكلية'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Bdepart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.department', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Btitle',
            field=models.CharField(max_length=200, verbose_name='عنوان الكتاب'),
        ),
    ]
