# Generated by Django 3.2.5 on 2021-07-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_alter_book_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/pdf'),
        ),
    ]
