# Generated by Django 3.2.4 on 2021-06-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=100)),
                ('contents', models.TextField(max_length=3000)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
