# Generated by Django 3.2.4 on 2021-06-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contents',
            field=models.TextField(max_length=10000),
        ),
    ]
